name: 1 - ğŸ—‚ï¸ test mock back

on: 
  push:
    branches: ["1-mock-livres"]

defaults: # Permet de metre par dÃ©fault le cd backend 
  run:
      working-directory: backend

jobs: 
  test: 
    name: ğŸ› ï¸test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸŒµCheckout repo
        uses: actions/checkout@v3

# install des dÃ©pendances 
      - name: ğŸˆInstallation des dÃ©pendances
        run: #|
          #cd backend
          npm install

      - name: ğŸ’« Lancement des tests backend
        run: npm run test:ci